name: Daily_Update
on:
  schedule:
    - cron: '0 0 * * *' # 每天早上執行
  workflow_dispatch: # 讓你可以手動按按鈕執行測試

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news.json
          git commit -m "Update news data" || exit 0
          git push
